language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
before_install: gem install bundler
before_script:
  - sh -c "if [ '$DB' = 'pg' ]; then psql -c 'create database acts_as_ordered_tree_test;' -U postgres; fi"
env:
  - DB=sqlite3
  #- DB=mysql
  - DB=pg
gemfile:
  - gemfiles/rails3.0.gemfile
  - gemfiles/rails3.1.gemfile
  - gemfiles/rails3.2.gemfile
script: "bundle exec rake spec"
notifications:
  recipients:
    - amikhailov83@gmail.com