pg:
  adapter: postgresql
  username: postgres
  database: acts_as_ordered_tree_test
  min_messages: ERROR
mysql:
  adapter: mysql2
  database: acts_as_ordered_tree_test
  username: travis
  encoding: utf8
sqlite3:
  adapter: sqlite3
  database: acts_as_ordered_tree.sqlite3.db