pg:
  adapter: postgresql
  database: acts_as_ordered_tree_test
  min_messages: ERROR
mysql:
  adapter: mysql2
  database: acts_as_ordered_tree_test
  username: root
  password:
  encoding: utf8
sqlite3:
  adapter: <%= "jdbc" if defined? JRUBY_VERSION %>sqlite3
  database: acts_as_ordered_tree.sqlite3.db